apiVersion: apps/v1
kind: Deployment
metadata:
  name: tarslog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tarslog
  template:
    metadata:
      labels:
        app: tarslog
    spec:
      containers:
      - name: tarslog
        image: ccr.ccs.tencentyun.com/tarsbase/tarslog:latest
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: tars-db-config
              key: DB_HOST
        livenessProbe:
            exec:
              command: ["tarscli", "hzcheck"]
            initialDelaySeconds: 5
            timeoutSeconds: 6
            periodSeconds: 8
        lifecycle:
          preStop:
            exec:
              command: ["tarscli", "prestop"]
