apiVersion: apps/v1
kind: Deployment
metadata:
  name: tarsstat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tarsstat
  template:
    metadata:
      labels:
        app: tarsstat
    spec:
      containers:
      - name: tarsstat
        image: ccr.ccs.tencentyun.com/tarsbase/tarsstat:latest
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: tars-db-config
              key: DB_HOST
        livenessProbe:
            exec:
              command: ["tarscli", "hzcheck"]
            initialDelaySeconds: 5
            timeoutSeconds: 6
            periodSeconds: 8
        lifecycle:
          preStop:
            exec:
              command: ["tarscli", "prestop"]
