apiVersion: apps/v1
kind: Deployment
metadata:
  name: tars-web
  labels:
    app: tars-web
spec:
  selector:
    matchLabels:
      app: tars-web
  replicas: 1
  template:
    metadata:
      labels:
        app: tars-web
    spec:
      containers:
      - name: tars-web
        image: ccr.ccs.tencentyun.com/tarsbase/tarsweb:v1.1.0
        ports:
          - containerPort: 3000
            hostPort: 30000
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: tars-db-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: tars-db-config
              key: DB_PORT
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: tars-db-config
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            configMapKeyRef:
              name: tars-db-config
              key: DB_PASS 
